apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: example-service
  name: example-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: example-service
status:
  loadBalancer: {}